🚀-release:
  stage: 🚀-release
  needs: [ 1️⃣-init-repository, 🏗-build ]
  script:
    - |
      yarn nx release publish
  rules:
    - if: $CI_PIPELINE_SOURCE != 'trigger' && $CI_COMMIT_TAG =~ /^release.*/
