name: 'Repository Initialization'
description: 'Initialize repository by checking out code and installing dependencies'

inputs:
  fetch-depth:
    description: 'Number of commits to fetch'
    required: false
    default: '0'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Init Repository
      shell: bash
      run: ./.github/actions/init/init.sh
      env:
        NX_MAX_WORKERS: 4
