name: Build Coday on push to master

on:
  push:
    branches:
      - master

env:
  NX_MAX_WORKERS: 4

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build app
        run: |
          yarn install --frozen-lockfile
          npx nx run web:build --parallel=$NX_MAX_WORKERS
