name: Build Coday on push to master

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INIT_REPOSITORY_PIPELINE_ID_ENV_FILE: "tmp.init-repository-pipeline-id"
  MASTER_BRANCH: master
  NX_MAX_WORKERS: 4
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  WORKING_DIRECTORY_PREFIX: ${{ secrets.WORKING_DIRECTORY_PREFIX }}

defaults:
  run:
    shell: bash

jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: biznet-io/github-actions/setup-working-directory@v1.2
      - uses: biznet-io/github-actions/init@v1.2

  build:
    runs-on: self-hosted
    needs: [init]
    steps:
      - uses: biznet-io/github-actions/setup-working-directory@v1.2
      - name: Build app
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          npx nx run web:build --parallel=$NX_MAX_WORKERS
