name: Build

on:
  push:
    branches:
      - master

env:
  NX_MAX_WORKERS: 4

jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/init-repo

  test:
    needs: [init]
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/tests
        with:
          is_merge_request: false
          base_ref: ${{ inputs.base_ref }}

  build:
    needs: [init, test]
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/build
