name: Build Coday on push to master

on:
  push:
    branches:
      - master

env:
  NX_MAX_WORKERS: 4

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: | 
          yarn install --frozen-lockfile
          yarn add sharp --platform=linux --architecture=x64

      - name: Build app
        run: |
          npx nx run web:build --parallel=$NX_MAX_WORKERS
