name: Repository Initialization

on:
  workflow_call:  # This allows other workflows to call this one

jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/init-repo
        with:
          node-version: '18'
          fetch-depth: 0