name: Merge Request

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]

env:
  NX_MAX_WORKERS: 4
  MASTER_BRANCH: master

jobs:
  init:
    runs-on: self-hosted
    steps:
      - name: Generate Commit Ref Slug
        id: slug
        run: |
          REF_NAME="${{ github.ref_name }}"
          SLUG=$(echo "$REF_NAME" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-' | sed 's/^-*\|-*$//g')
          echo "WORKING_DIRECTORY=$SLUG" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          path: ${{ env.WORKING_DIRECTORY }}
          sparse-checkout: |
            .github
      - uses: ./.github/actions/init
        with:
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
      - uses: ./.github/actions/tests
        with:
          is_merge_request: true
          base_ref: ${{ inputs.base_ref }}
