name: Merge Request

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]

env:
  NX_MAX_WORKERS: 4
  MASTER_BRANCH: master

jobs:
  generate-slug:
    runs-on: ubuntu-latest
    outputs:
      slug: ${{ steps.slugify.outputs.slug }}
    steps:
      - name: Generate Commit Ref Slug
        id: slugify
        run: |
          REF_NAME="${{ github.ref_name }}"
          SLUG=$(echo "$REF_NAME" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-' | sed 's/^-*\|-*$//g')
          echo "slug=$SLUG" >> $GITHUB_OUTPUT

  init:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ needs.generate-slug.outputs.slug }}
          sparse-checkout: |
            .github
      - uses: ./.github/actions/init
        with:
          WORKING_DIRECTORY: ${{ needs.generate-slug.outputs.slug }}
      - uses: ./.github/actions/tests
        with:
          WORKING_DIRECTORY: ${{ needs.generate-slug.outputs.slug }}
          is_merge_request: true
          base_ref: ${{ inputs.base_ref }}
