name: Merge Request

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INIT_REPOSITORY_PIPELINE_ID_ENV_FILE: "tmp.init-repository-pipeline-id"
  MASTER_BRANCH: master
  NX_MAX_WORKERS: 4
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  WORKING_DIRECTORY:

defaults:
  run:
    shell: bash
    working-directory: ${{ env.WORKING_DIRECTORY }}

jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: biznet-io/github-actions/init@v1
        with:
          base_ref: $GITHUB_HEAD_REF
          is_merge_request: true

  tests:
    runs-on: self-hosted
    needs:
      - init
    steps:
      - uses: biznet-io/github-actions/setup-working-directory@v1
      - name: Run tests
        run: |
          yarn nx affected --base=origin/${GITHUB_HEAD_REF} --head=HEAD --target="lint,test" --parallel=$NX_MAX_WORKERS
