name: Merge Request

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]

env:
  NX_MAX_WORKERS: 4
  MASTER_BRANCH: master

jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            package.json
      - uses: ./.github/actions/init
      - uses: ./.github/actions/tests
        with:
          is_merge_request: true
          base_ref: ${{ inputs.base_ref }}
