name: Merge Request

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]

env:
  NX_MAX_WORKERS: 4
  MASTER_BRANCH: master
  INIT_REPOSITORY_PIPELINE_ID_ENV_FILE: "tmp.init-repository-pipeline-id"

defaults:
  run:
    shell: bash

jobs:
  init:
    runs-on: self-hosted
    outputs:
      WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Set workflow-wide variable
        run: |
          echo "WORKING_DIRECTORY=${GITHUB_WORKSPACE}/${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - uses: biznet-io/github-actions/init@v1
        with:
          WORKING_DIRECTORY: ${{env.WORKING_DIRECTORY}}
          is_merge_request: true
          base_ref: $GITHUB_HEAD_REF

  tests:
    runs-on: self-hosted
    needs:
      - init
    steps:
      - uses: biznet-io/github-actions/tests@v1
        with:
          WORKING_DIRECTORY: ${{needs.init.outputs.WORKING_DIRECTORY}}
          is_merge_request: true
          base_ref: $GITHUB_HEAD_REF
