name: Release

on:
  push:
    tags:
      - 'release'

env:
  NX_MAX_WORKERS: 4
  MASTER_BRANCH: master

jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-repo

  build:
    needs: [init]
    if: startsWith(github.ref, 'refs/tags/release')
    uses: ./.github/workflows/build.yml

  release:
    needs: [build]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/release
