name: Release

on:
  push:
    tags:
      - 'release'


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INIT_REPOSITORY_PIPELINE_ID_ENV_FILE: "tmp.init-repository-pipeline-id"
  MASTER_BRANCH: master
  NX_MAX_WORKERS: 4
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

defaults:
  run:
    shell: bash

jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-repo

  build:
    needs: [init]
    if: startsWith(github.ref, 'refs/tags/release')
    uses: ./.github/workflows/build.yml

  release:
    needs: [build]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/release

jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: biznet-io/github-actions/init@v1

  tests:
    runs-on: self-hosted
    needs:
      - init
    steps:
      - uses: biznet-io/github-actions/tests@v1
        with:
          base_ref: $GITHUB_HEAD_REF
          is_merge_request: true
