name: Release Coday on NPM

on:
  push:
    tags:
      - 'release/*'

env:
  NPM_CONFIG_PROVENANCE: true
  NX_MAX_WORKERS: 4

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    steps:
      - uses: actions/checkout@v4
      - name: Publish release
        run: |
          yarn install --frozen-lockfile
          npm config set //${{ vars.NPM_REGISTRY }}/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}
          npx nx release publish --registry=https://${{ vars.NPM_REGISTRY }}
          npm config delete //${{ vars.NPM_REGISTRY }}/:_authToken
