name: Release Coday on NPM

on:
  push:
    tags:
      - 'release/*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INIT_REPOSITORY_PIPELINE_ID_ENV_FILE: "tmp.init-repository-pipeline-id"
  MASTER_BRANCH: master
  NX_MAX_WORKERS: 4
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: biznet-io/github-actions/setup-working-directory@v1
      - uses: biznet-io/github-actions/init@v1
        with:
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}

  release:
    runs-on: self-hosted
    needs: [init]
    steps:
      - uses: biznet-io/github-actions/setup-working-directory@v1
      - name: Publish release
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          yarn nx release publish
