name: Test

on:
  workflow_call:
    inputs:
      is_merge_request:
        required: false
        type: boolean
        default: false
      base_ref:
        required: false
        type: string
        default: ''

env:
  NX_MAX_WORKERS: 4
  MASTER_BRANCH: master

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Run tests
        run: |
          if [ "${{ inputs.is_merge_request }}" = "true" ]; then
            yarn nx affected --base=origin/${{ inputs.base_ref }} --head=HEAD --target="lint,test" --parallel=${{ env.NX_MAX_WORKERS }}
          else
            yarn nx run-many --target="lint,test" --parallel=${{ env.NX_MAX_WORKERS }}
          fi