name: Validate Coday on pull requests

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ master ]

env:
  NX_MAX_WORKERS: 4

defaults:
  run:
    shell: bash

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      # Cache Yarn dependencies
      - name: Cache Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/cache
            .yarn/cache
            node_modules/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: |
          npx nx affected --base=origin/${GITHUB_BASE_REF} --head=HEAD --target="lint,test" --parallel=$NX_MAX_WORKERS

      - name: Build app
        run: |
          yarn install --frozen-lockfile
          npx nx run web:build --parallel=$NX_MAX_WORKERS
