name: Validate Coday on pull requests

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INIT_REPOSITORY_PIPELINE_ID_ENV_FILE: "tmp.init-repository-pipeline-id"
  MASTER_BRANCH: master
  NX_MAX_WORKERS: 4
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  WORKING_DIRECTORY_PREFIX: ${{ secrets.WORKING_DIRECTORY_PREFIX }}

defaults:
  run:
    shell: bash

jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: biznet-io/github-actions/setup-working-directory@v1.1
      - uses: biznet-io/github-actions/init@v1.1
        with:
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}

  tests:
    runs-on: self-hosted
    needs: [ init ]
    steps:
      - uses: biznet-io/github-actions/setup-working-directory@v1.1
      - name: Run tests
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          npx nx affected --base=origin/${GITHUB_HEAD_REF} --head=HEAD --target="test" --parallel=$NX_MAX_WORKERS

  build:
    runs-on: self-hosted
    needs: [ init ]
    steps:
      - uses: biznet-io/github-actions/setup-working-directory@v1.1
      - name: Build app
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          npx nx run web:build --parallel=$NX_MAX_WORKERS
