name: Validate Coday on pull requests

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INIT_REPOSITORY_PIPELINE_ID_ENV_FILE: "tmp.init-repository-pipeline-id"
  MASTER_BRANCH: master
  NX_MAX_WORKERS: 4
  WORKING_DIRECTORY_PREFIX: validate

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          yarn install --frozen-lockfile
          npx nx affected --base=origin/${GITHUB_BASE_REF} --head=HEAD --target="lint,test" --parallel=$NX_MAX_WORKERS

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build app
        run: |
          yarn install --frozen-lockfile
          npx nx run web:build --parallel=$NX_MAX_WORKERS
